//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//
package wangyijieholding.agendaapplication.userpools;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;

import com.amazonaws.mobile.user.signin.CognitoUserPoolsSignInProvider;
import wangyijieholding.agendaapplication.R;
import wangyijieholding.agendaapplication.util.ViewHelper;

/**
 * Activity to prompt for account sign up information.
 */
public class SignUpActivity extends Activity {
    /** Log tag. */
    private static final String LOG_TAG = SignUpActivity.class.getSimpleName();

    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);
    }

    /**
     * Retrieve input and return to caller.
     * @param view the Android View
     */
    public void signUp(final View view) {
        final String username = ViewHelper.getStringValue(this, R.id.signup_username);
        final String password = ViewHelper.getStringValue(this, R.id.signup_password);
        final String email = ViewHelper.getStringValue(this, R.id.signup_email);

        Log.d(LOG_TAG, "username = " + username);
        Log.d(LOG_TAG, "email = " + email);

        if(passwordIsValid(password)) {
            final Intent intent = new Intent();
            intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.USERNAME, username);
            intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.PASSWORD, password);
            intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.GIVEN_NAME, "");
            intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.EMAIL_ADDRESS, email);
            intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.PHONE_NUMBER, "");

            setResult(RESULT_OK, intent);
            finish();
        } else {
            TextView passwordRequirement = (TextView)findViewById(R.id.password_requirement_hint);
            passwordRequirement.setTextColor(Color.RED);
            ViewHelper.setStringValue(this,R.id.signup_password,"");
        }
    }

    public boolean passwordIsValid(String password){
        boolean validPassword;
        boolean containsLetter = false;
        boolean containsNumber = false;
        if(password.length() > 7){
            for (int i = 0; i < password.length(); i++){
                if (Character.isLetter(password.charAt(i))){
                    containsLetter = true;
                }
                if (Character.isDigit(password.charAt(i))){
                    containsNumber = true;
                }
            }
        }
        validPassword = containsLetter && containsNumber;
        return validPassword;
    }
}
