//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub a6794b3e-8bc8-4a24-b53f-f1411e6d9377 aws-my-sample-app-android-v0.10";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:971533db-f35b-420f-82eb-f01ce90a5f3a";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "hiveagenda-userfiles-mobilehub-1604625755";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-east-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_mr1ryvw8n";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "1ght6b13v92i6n481ah7bpmd3e";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "12dr5eefs5p0iipip0vm2p1tcsl4j6t3pc8h3qq9hv2f0f6aqg09";
}
