//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub d761d359-9e90-443b-8dac-cd3ae5738d4c aws-my-sample-app-android-v0.10";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:267edbca-9074-4250-bec6-8d3d56bedd4b";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "hicalendar-userfiles-mobilehub-1821985301";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-east-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_E57tTtEvz";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "3508ll0asinghgpq7tib26uq28";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "726kk4p8ap2o1su4hes6j5n6q017hn7pbfjkhpgprjs351lfe1l";
}
